version: "3.9"
services:
  galaxy:
    image: ghcr.io/uomresearchit/galaxy:latest
    restart: unless-stopped
    container_name: omniverse-galaxy
    ports:
      - 8080:8080
    volumes:
      - omni-galaxy-storage:/galaxy/server/
      - ./galaxy-tools:/galaxy/server/tools/
      - ./galaxy-config/tool_conf.xml:/galaxy/server/config/tool_conf.xml.sample
      - ./galaxy-config/job_conf.xml:/galaxy/server/config/job_conf.xml.sample_basic
      - ./galaxy-config/galaxy.yml:/galaxy/server/config/galaxy.yml 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
volumes:
  omni-galaxy-storage: